### ISSUE TITLE
Add Apple as a login option 

### ISSUE THREAD

**Issue by xristy** [buda-base/bdrc-auth-policies#5]
Apple needs to be added to the Auth0 login panel.

**Comment by MarcAgate** [comment]
I am not sure we are ready for that, unless I don't understand what the instructions below mean.

**Register Apps in the Apple Developer Portal**

**Before you configure an Apple social connection in the Auth0 Dashboard, you need to set up your application on your Apple Developer account in the Apple Developer Portal**. Once that is complete, you can use the assigned credentials you receive from Apple to set up your Apple connection in the Auth0 Dashboard.

After you register your application, you will be given the following IDs and keys to use in the application connection settings in the Dashboard:

Services ID (Client ID)
Apple Team ID
Client Secret Signing Key
Key ID
Prerequisites
**Before you can register your app in the Apple Developer Portal, you must have an Apple Developer account, which is a paid account with Apple. (There is no free trial available unless you are part of their iOS Developer University Program.)**


https://auth0.com/docs/connections/apple-siwa/set-up-apple?_ga=2.100270494.1607212575.1593698972-1035611516.1588160076

**Comment by xristy** [comment]
Don’t bother with this now. I’ll take care of it in a while. 

BTW, Baidu has been added as a connection but doesn’t appear on the login screen, at least for me on lib-dev. I assume it needs to be enabled in UI

**Comment by MarcAgate** [comment]
Same issue with Baidu as for Apple, except it's (apparently) free. But the link given by auth0 to integrate with Baidu is broken, and I haven't found so far any page allowing for this either in english or in french (in chinese it is tough !). But still I don't understand why "LinkedIn" - not declared as a connection - appears anyway as a login option (same remark for Microsoft  Account and Github)...

**Comment by xristy** [comment]
The Baidu is showing as added to the bdrc-io tenant so I think it just needs to be enabled, if not already, in the login UI unless I'm on the wrong tenant:

![Screen Shot 2020-07-02 at 12 51 01 PM](https://user-images.githubusercontent.com/3542294/86393513-cc61cd80-bc62-11ea-878a-eb52d8b06a0c.png)

As far as I can tell the login option is currently not available on the [library](https://library.bdrc.io).

Further, we already seem to have around 110 users that have registered.

**Comment by MarcAgate** [comment]
I know Baidu is a possible connection, that it has been added and also that it has not been correctly setup at enabling time since I wrote earlier that I tried unsuccessfully to make it work  :


![capture](https://user-images.githubusercontent.com/13099449/86395256-f40a6300-bc6d-11ea-920a-98c9b5035ffc.jpeg)

So, when you say "it just needs to be enabled", then just tell me how, because while I enabled applications to be accessed through Baidu, I still have no idea about how to proceed to enable this connection despite my investigations and because links in auth0 docs to Baidu integration portal are broken. I am surprised it's been added and not enabled. 
On the opposite, as I sais already, I don't understand why "LinkedIn" - not declared as a connection - appears anyway as a login option (same remark for Microsoft Account and Github)...

EDIT: I finally found a valid link to baidu portal that actually led me to where I went this AM. Despite the failing "english" version I finally understood that I need to have some sort of dev account... 
https://passport.baidu.com/v2/?reg&tpl=newdev&overseas=1&u=https://developer.baidu.com/dev

Anyway... I should be able to use this connection with auth0 dev keys... But for now , I need to know where to set up the universal Login page displaying baidu option.  For now, login butto are disabled on library and library-dev, so I cannot see how it looks and which url it calls nor I can figure out the parameters it is using.

**Comment by xristy** [comment]
Sorry I misunderstood you. I thought you were saying that some link on the auth0 social connections page pointing to the Baidu instructions was broken:
> the link given by auth0 to integrate with Baidu is broken

So I guessed, incorrectly, that you weren't the one that had added the Baidu connection.

We can revisit this after login is once again enabled.

**Comment by MarcAgate** [comment]
I did not setup Baidu, 

>  I am surprised it's been added and not enabled.

I just tried at your demand, to make it work !

**Comment by xristy** [comment]
Perhaps we should just close this. I didn't demand anything!

**Comment by MarcAgate** [comment]
Well, aren't we planning to have Apple connection setup ? If so, let's keep this open. Besides, We need to know how LinkedIn and Microsoft ended up on our login page while not being set up as connection while having baidu not appearing despite being set as a possible connection. 
@berger-n What is the full Url (and payload ?) of your call to /authorize auth0 API endpoint ?

**Comment by jimk-bdrc** [comment]
We are already members of the Apple Developer program. I am the admin, and various people are members (almost nobody on this thread).

**Comment by xristy** [comment]
Thanks Jim. I thought I recalled you having set up the organizarion developer account. I'll touch base with you about creds (perhaps they're my personal AppleId creds). In any event I'll see about working through adding the connection. I'm pretty sure I'm the one that set up the Google connection.

Once the connection is setup, adding to the login UI should very quick.

**Comment by berger-n** [comment]
you can now use [library-dev](http://library-dev.bdrc.io/) to test 
(login has been disabled on library.bdrc.io until user profile has been updated with Tania's design)

from what I see Baidu login is active:
![image](https://user-images.githubusercontent.com/33383857/86453747-908c3e00-bd1e-11ea-9bae-47d060a561a5.png)

**Comment by MarcAgate** [comment]
Excellent ! Thanks

**Comment by xristy** [comment]
I have setup Apple as a social connection w/ all apps enabled as for google and baidu. 

@berger-n, I assume that there is some small work to be done so it show up as an option on the login screen.

**Comment by berger-n** [comment]
some [update](https://auth0.com/blog/try-sign-in-with-apple-in-your-auth0-apps-today/#Add-Sign-In-with-Apple-to-Your-Applications) of the js scripts was needed indeed
it should work now (on [library-dev](http://library-dev.bdrc.io/))

![image](https://user-images.githubusercontent.com/33383857/87550595-84559880-c6af-11ea-8843-5c1d1cf2bcaa.png)

**Comment by xristy** [comment]
Excellent! Thanks @berger-n.
